version: '3.5'
services:
  proxy-80:
    image: hpello/tcp-proxy
    depends_on:
      - sync_server
    ports:
      - "80:80"
    networks:
      - default
      - internal
    command: sync_server 80

  proxy-27021:
    image: hpello/tcp-proxy
    depends_on:
      - sync_server
    ports:
      - "27021:27021"
    networks:
      - default
      - internal
    command: sync_server 27021

  mongodb_container:
    image: mongo:5.0
    volumes:
      - mongodb_data_container:/data/db
    command: "--replSet rs0"
    restart: unless-stopped
    networks:
      - internal

  replSetInit:
    image: mongo:5.0
    restart: on-failure
    depends_on:
      - mongodb_container
    links:
      - mongodb_container
    command:
      - /bin/sh
      - -c
      - |
        mongosh --host mongodb_container:27017 --eval 'rs.isMaster().ismaster || rs.initiate({
          "_id": "rs0",
          "members" : [
            { "_id" : 0, "host" : "mongodb_container:27017" }
          ]
        })'
    networks:
      - internal

  sync_server:
    image: quay.io/mongodb/tiered-sync-server:v0.18.2
    # platform: linux/amd64
    depends_on:
      - mongodb_container
      - replSetInit
    links:
      - mongodb_container
    volumes:
      - ./build/edge_config.json:/apps/configs/edge_config.json
      - edge_logs:/app/edge_logs
    environment:
      EDGE_CONFIG_FILE: /apps/configs/edge_config.json
    restart: unless-stopped
    networks:
      - default
      - internal

  vector:
    image: quay.io/mongodb/edge-vector:v0.18.2
    volumes:
      - edge_logs:/home/edge_logs
    environment:
      CLIENT_APP_ID: inventory_management_demo-uhetl
      EDGE_TOKEN: 65b8f4c917201be4b075ee00
      CLOUD_BASE_URL: https://services.cloud.mongodb.com
    restart: unless-stopped
    networks:
      - default

volumes:
  mongodb_data_container:
  edge_logs:

networks:
  internal:
    internal: true
  default:
